### ISSUE TITLE
Testing with mocha / proxyquire

### ISSUE THREAD

**Issue by cif** [AntJanus/babel-plugin-namespaces#12]
This is more of a question than an issue. We have a larger project and often re-organize as directories grow so this plugin would be extremely helpful. 

We use https://github.com/thlorenz/proxyquire to smash dependencies in our unit tests. Has anyone had a need to get `<ns>` syntax transpiled other places than require e.g: 

```
const builderApi = proxyquireStrict('./builderApi', {
    './aggregateBuildData': aggregateBuildData,
    '<config>/': appConfig,
    '<redux-modules>/product/productActions': { answerQuestion, fetchProduct }
  });
```

**Comment by cif** [comment]
Update for anyone else who may run into an issue: This will work fine the issue was that mocha requires `.babelrc` it will not read the babel plugin configuration specified in `package.json`.

**Comment by cif** [comment]
Sorry for false positive on solution. It's still not working someone pushed a `.only` into test suite which made it look to be working

**Comment by AntJanus** [comment]
I haven't used proxyquire, and honestly, haven't used this outside of require. The plugin replaces only import/require paths, nowhere else. You can check the code and see the visitor setup to do that. 

For outside uses, you can either add the functionality, or use parts of the code you care about and directly apply it (pass in the string with the `<ns>` path and get the right result back).

**Comment by cif** [comment]
I did exactly what you said and ended up creating [babel-plugin-proxyquire-namespace](https://www.npmjs.com/package/babel-plugin-proxyquire-namespace). 

After looking at the code I initially thought about creating a PR for this plugin which would allow an array of function names as a config option however, the AST is quite different from simple args[0] string rawValue vs the second argument object keys needing to be replaced in the case of proxyquire.
